import { Inter } from "next/font/google";
import "./globals.css";
import React from "react";
import 'bootstrap/dist/css/bootstrap.min.css';
import Image from "next/image";
import Navbar from "@/components/nav";
import BootstrapClient from "@/components/BootstrapClient";
import Carousel from "@/components/Carousel";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}><BootstrapClient/>
      <Navbar/>
      <Carousel/>
      {children}
      
      </body>
      
    </html>
  );
}
